### ISSUE TITLE
OutOfMemoryError during dataset discovery

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/n5-ij#17]
```
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.janelia.saalfeldlab.n5.N5DatasetDiscoverer.discoverThreadsHelper(N5DatasetDiscoverer.java:141)
	at org.janelia.saalfeldlab.n5.N5DatasetDiscoverer.access$100(N5DatasetDiscoverer.java:51)
	at org.janelia.saalfeldlab.n5.N5DatasetDiscoverer$1$1.call(N5DatasetDiscoverer.java:167)
	at org.janelia.saalfeldlab.n5.N5DatasetDiscoverer$1$1.call(N5DatasetDiscoverer.java:163)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: unable to create new native thread
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog$LoaderSorterAndCallback.run(DatasetSelectorDialog.java:609)
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
```

**Comment by bogovicj** [comment]
Have not been able to reproduce, and dataset discovery implementation has changed after `deepList`. Closing.
