### ISSUE TITLE
h5 parsing throws errors and fails

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/n5-ij#18]
```
java.util.concurrent.ExecutionException: java.io.IOException: ncsa.hdf.hdf5lib.exceptions.HDF5SymbolTableException: Symbol table:Inappropriate type ["H5Gint.c line 327 in H5G__open_name(): not a group"]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog$LoaderSorterAndCallback.run(DatasetSelectorDialog.java:609)
Caused by: java.io.IOException: ncsa.hdf.hdf5lib.exceptions.HDF5SymbolTableException: Symbol table:Inappropriate type ["H5Gint.c line 327 in H5G__open_name(): not a group"]
	at org.janelia.saalfeldlab.n5.hdf5.N5HDF5Reader.list(N5HDF5Reader.java:217)
	at org.janelia.saalfeldlab.n5.N5DatasetDiscoverer$1.call(N5DatasetDiscoverer.java:153)
	at org.janelia.saalfeldlab.n5.N5DatasetDiscoverer$1.call(N5DatasetDiscoverer.java:142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: ncsa.hdf.hdf5lib.exceptions.HDF5SymbolTableException: Symbol table:Inappropriate type ["H5Gint.c line 327 in H5G__open_name(): not a group"]
	at ch.systemsx.cisd.hdf5.hdf5lib.H5.H5Gopen(Native Method)
	at ch.systemsx.cisd.hdf5.hdf5lib.H5GLO.H5Gopen(H5GLO.java:80)
	at ch.systemsx.cisd.hdf5.HDF5.openGroup(HDF5.java:322)
	at ch.systemsx.cisd.hdf5.HDF5$10.call(HDF5.java:423)
	at ch.systemsx.cisd.hdf5.HDF5$10.call(HDF5.java:1)
	at ch.systemsx.cisd.hdf5.cleanup.CleanUpCallable.call(CleanUpCallable.java:40)
	at ch.systemsx.cisd.hdf5.HDF5.getGroupMembers(HDF5.java:436)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.getAllGroupMembers(HDF5BaseReader.java:773)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.getGroupMembers(HDF5BaseReader.java:761)
	at ch.systemsx.cisd.hdf5.HDF5ObjectReadOnlyInfoProviderHandler.getGroupMembers(HDF5ObjectReadOnlyInfoProviderHandler.java:424)
	at org.janelia.saalfeldlab.n5.hdf5.N5HDF5Reader.list(N5HDF5Reader.java:214)
```

**Comment by bogovicj** [comment]
fixed by https://github.com/saalfeldlab/n5-ij/commit/51783c3bbaccb6c05084d3630d9b0578ba02a7d4
