### ISSUE TITLE
Export of RGB types fails

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/n5-ij#25]
Should RGB images be written as `int32` images (`rgba`)? or as 3-channel `uint8` images? or prompt user for a choice?

```
Exception in thread "main" java.lang.NullPointerException
	at org.janelia.saalfeldlab.n5.DatasetAttributes.asMap(DatasetAttributes.java:103)
	at org.janelia.saalfeldlab.n5.N5Writer.setDatasetAttributes(N5Writer.java:84)
	at org.janelia.saalfeldlab.n5.N5Writer.createDataset(N5Writer.java:133)
	at org.janelia.saalfeldlab.n5.imglib2.N5Utils.save(N5Utils.java:1273)
	at org.janelia.saalfeldlab.n5.ij.N5Exporter.writeSplitChannels(N5Exporter.java:248)
	at org.janelia.saalfeldlab.n5.ij.N5Exporter.process(N5Exporter.java:205)
	at org.janelia.saalfeldlab.n5.ij.N5Exporter.run(N5Exporter.java:280)
	at org.janelia.saalfeldlab.n5.demos.runImageJBogo.main(runImageJBogo.java:70)
```

**Comment by bogovicj** [comment]
## Why this error happens

* `imglib2-ij` wraps RGB `ImagePlus`s as `IntImagePlus< ARGBType >` [see here](https://github.com/imglib/imglib2-ij/blob/7a6288fcc741625c2c277fab7d754c232f549e9c/src/main/java/net/imglib2/img/ImagePlusAdapter.java#L183-L197)
* `N5Utils` doesn't return a valid n5type for the imglib2 `ARGBType` [see here](https://github.com/saalfeldlab/n5-imglib2/blob/ffeb7007daa82b45aba09cbcf2c760cddce50981/src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5Utils.java#L108-L129)

## Ideas
1) Modify `N5Utils.dataType` to return
  * `INT32` (OR `UINT32`?)
  * return a new `ARGB` `Datatype` (that uses an `IntArrayDataBlock`)
2) Split the R-G-B channels and write separately as `uint8` 
3) Detect RGB in n5-ij, convert to `UINT32`, and keep track in other metadata

**Comment by axtimwalde** [comment]
It should save it as uint32 (ARGB), may be add an additional ImageJ specific property that indicates that this is to be interpreted as ARGB? The loader can then naively convert.

**Comment by bogovicj** [comment]
> additional ImageJ specific property 

Exactly, that's what I was thinking.  This will work for the "ImageJ" metadata style, but not "cosem" for example.

**Comment by bogovicj** [comment]
Done https://github.com/saalfeldlab/n5-ij/commit/9f0759bf233905e4a44b82aa31070238a96a5b07
