### ISSUE TITLE
Can't open n5-viewer after fiji update_error relate to "net/imglib2/display/RealARGBColorConverter$Imp0"

### ISSUE THREAD

**Issue by wangyuhan01** [saalfeldlab/n5-ij#4]
The n5-viewer throws the following error after updating Fiji.  

java.lang.NoClassDefFoundError: net/imglib2/display/RealARGBColorConverter$Imp0
	at org.janelia.saalfeldlab.n5.bdv.N5Viewer.addSourceToListsRealType(N5Viewer.java:279)
	at org.janelia.saalfeldlab.n5.bdv.N5Viewer.addSourceToListsGenericType(N5Viewer.java:242)
	at org.janelia.saalfeldlab.n5.bdv.N5Viewer.exec(N5Viewer.java:133)
	at org.janelia.saalfeldlab.n5.bdv.N5Viewer.run(N5Viewer.java:88)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)

**Comment by igorpisarev** [comment]
@wangyuhan01 I've updated the dependencies so now N5 Viewer should work with most recent Fiji. Please check out and install the updated version of the plugin from https://github.com/saalfeldlab/n5-viewer

**Comment by wangyuhan01** [comment]
Thank you so much! It works now with the new update.

**Comment by igorpisarev** [comment]
@wangyuhan01 Great!
Can you please close this issue? I don't seem to have permissions in this repository.
