### ISSUE TITLE
NullPointerException after browse

### ISSUE THREAD

**Issue by krokicki** [saalfeldlab/n5-ij#43]
I'm getting a new NullPointerException after browsing to an n5 and opening it:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.lambda$null$10(DatasetSelectorDialog.java:620)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

The n5 I'm opening is an export output generated by https://github.com/saalfeldlab/stitching-spark

The n5 seems to load correctly in the Main tab but nothing is loaded in the other tabs. So I'm not sure if this is a real issue, because viewing seem to work okay afterwards, but the exception just seems worrisome.

**Comment by bogovicj** [comment]
Thanks for reporting

**Comment by bogovicj** [comment]
confirming this is now fixed
