### ISSUE TITLE
Paintera label-multiset datasets cannot be opened

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/n5-ij#63]
Datasets of type label-multiset should be open-able by imagej, it should convert to an integer type.

(Found by @jonesa3)

Metadata are parsed and the UI let's you select a label-multiset typed dataset, but whey opening, throws 
<details>

<summary>this error trace</summary>

```
Exception in thread "AWT-EventQueue-1" java.lang.UnsupportedOperationException
	at net.imglib2.type.label.LabelMultisetType.getNativeTypeFactory(LabelMultisetType.java:170)
	at net.imglib2.img.imageplus.ImagePlusImgFactory.create(ImagePlusImgFactory.java:69)
	at net.imglib2.img.imageplus.ImagePlusImgFactory.create(ImagePlusImgFactory.java:76)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.read(N5Importer.java:489)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.process(N5Importer.java:624)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.process(N5Importer.java:596)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.process(N5Importer.java:651)
	at org.janelia.saalfeldlab.n5.ij.N5Importer$1.run(N5Importer.java:688)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.processThread(N5Importer.java:691)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.datasetSelectorCallBack(N5Importer.java:372)
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.ok(DatasetSelectorDialog.java:756)
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.lambda$6(DatasetSelectorDialog.java:320)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:262)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
<details>

**Comment by bogovicj** [comment]
Should work after https://github.com/saalfeldlab/n5-ij/commit/3634c140ac72c6a5920338c049fb5735d631468d

![n5-ij-label-multiset-open](https://github.com/saalfeldlab/n5-ij/assets/6912043/6e6902a9-fd92-4a89-8662-2829fc958143)
