### ISSUE TITLE
Intermittent test failure

### ISSUE THREAD

**Issue by ctrueden** [saalfeldlab/n5-ij#75]
When running the pom-scijava melting pot, the n5-ij component sometimes fails tests with the exception:

```
java.lang.AssertionError: /cosem_ms
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.janelia.saalfeldlab.n5.metadata.MetadataTests.testCosemMetadataMultiscale(MetadataTests.java:58)
```

To work around this, I just rerun the CI build and it usually passes the next time. But it would be nice if this could be made more robust. Any ideas what might be going on here?

**Comment by bogovicj** [comment]
> But it would be nice if this could be made more robust. Any ideas what might be going on here?

Agreed, will investigate
