### ISSUE TITLE
Support for non-standard port numbers

### ISSUE THREAD

**Issue by krokicki** [saalfeldlab/n5-ij#81]
When I try to open an N5 that lives on an S3 Proxy with a port number other than 80/443 (e.g. `https://rokickik-dev.int.janelia.org:8000`), it throws an exception (see below). When I run the proxy on port 443 (e.g. `https://rokickik-dev.int.janelia.org`), this error goes away. It looks like it's inserting brackets into the hostname before parsing.

```
(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Mac OS X 10.16; 1677MB of 65435MB (2%)
 
org.janelia.saalfeldlab.n5.N5Exception: Could not create s3 client from uri: https://rokickik-dev.int.janelia.org:8000
	at org.janelia.saalfeldlab.n5.universe.N5Factory.createS3(N5Factory.java:208)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.newAmazonS3KeyValueAccess(N5Factory.java:109)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.access$200(N5Factory.java:80)
	at org.janelia.saalfeldlab.n5.universe.N5Factory$KeyValueAccessBackend.lambda$static$3(N5Factory.java:582)
	at org.janelia.saalfeldlab.n5.universe.N5Factory$KeyValueAccessBackend.apply(N5Factory.java:601)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.getKeyValueAccess(N5Factory.java:232)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.openN5Container(N5Factory.java:536)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.openN5Container(N5Factory.java:558)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.openReader(N5Factory.java:349)
	at org.janelia.saalfeldlab.n5.ij.N5Importer$N5ViewerReaderFun.apply(N5Importer.java:871)
	at org.janelia.saalfeldlab.n5.ij.N5Importer$N5ViewerReaderFun.apply(N5Importer.java:847)
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.openContainer(DatasetSelectorDialog.java:633)
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.lambda$run$4(DatasetSelectorDialog.java:332)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.janelia.saalfeldlab.n5.N5Exception: Could not create s3 client from uri: https://rokickik-dev.int.janelia.org:8000
	at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:132)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.createS3(N5Factory.java:206)
	... 48 more
Caused by: java.net.URISyntaxException: Malformed IPv6 address at index 9: https://[rokickik-dev.int.janelia.org:8000]
	at java.net.URI$Parser.fail(URI.java:2873)
	at java.net.URI$Parser.parseIPv6Reference(URI.java:3494)
	at java.net.URI$Parser.parseServer(URI.java:3244)
	at java.net.URI$Parser.parseAuthority(URI.java:3180)
	at java.net.URI$Parser.parseHierarchical(URI.java:3122)
	at java.net.URI$Parser.parse(URI.java:3078)
	at java.net.URI.<init>(URI.java:673)
	at java.net.URI.<init>(URI.java:774)
	at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:129)
	... 49 more
```

**Comment by cmhulbert** [comment]
We talked offline, but it seems this works better in the most up-to-date versions. @krokicki feel free to reopen if any of the issues show up again
