### ISSUE TITLE
Allow browsing folders via HTTPS/S3 URIs 

### ISSUE THREAD

**Issue by krokicki** [saalfeldlab/n5-ij#87]
With a local file system, you can open any directory (by the spec, any directory is an N5) and it will nicely show all of the N5 contents, even when there are multiple .n5 folders underneath, e.g.

![Screenshot 2024-07-23 at 1 02 52 PM](https://github.com/user-attachments/assets/d0e6bf2b-7215-4875-b0b6-1efbfacebdaf)

This is extremely useful for opening two data sets which are in separate n5 directories. 

However, this doesn't work if the data is on an S3-like filesystem. Trying to mount the same directory via VAST S3 (i.e. `https://nrs.int.janelia.org/scicompsoft/rokicki/flyefish/output4/`) results in a "java.lang.IllegalArgumentException: bucketName cannot be empty" error:

```
(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Mac OS X 10.16; 3667MB of 43911MB (8%)
 
org.janelia.saalfeldlab.n5.N5Exception: Could not create s3 client from uri: https://nrs.int.janelia.org
	at org.janelia.saalfeldlab.n5.universe.N5Factory.createS3(N5Factory.java:219)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.newAmazonS3KeyValueAccess(N5Factory.java:114)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.access$200(N5Factory.java:84)
	at org.janelia.saalfeldlab.n5.universe.N5Factory$KeyValueAccessBackend.lambda$static$3(N5Factory.java:593)
	at org.janelia.saalfeldlab.n5.universe.N5Factory$KeyValueAccessBackend.apply(N5Factory.java:612)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.getKeyValueAccess(N5Factory.java:243)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.openN5Container(N5Factory.java:547)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.openN5Container(N5Factory.java:569)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.openReader(N5Factory.java:360)
	at org.janelia.saalfeldlab.n5.ij.N5Importer$N5ViewerReaderFun.apply(N5Importer.java:1048)
	at org.janelia.saalfeldlab.n5.ij.N5Importer$N5ViewerReaderFun.apply(N5Importer.java:1018)
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.openContainer(DatasetSelectorDialog.java:643)
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.lambda$run$4(DatasetSelectorDialog.java:340)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: bucketName cannot be empty
	at com.amazonaws.util.ValidationUtils.assertStringNotEmpty(ValidationUtils.java:89)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExistV2(AmazonS3Client.java:1406)
	at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:219)
	at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:182)
	at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:138)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.createS3(N5Factory.java:217)
	... 48 more
```

You can open any of the folders with a ".n5" suffix, but not the parent directory.

**Comment by krokicki** [comment]
Updated test data..
Works: https://s3.janelia.org/opendata/flyefish/NP08_R2_5_5_SS89446_Lk_Eh_546_NPF_Trissin_647_1x_ROL.zarr
Doesn't work: https://s3.janelia.org/opendata/flyefish
